# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '0717Test' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 0717Test

pod 'Colorify'
pod 'Alamofire', '~> 4.7'
pod 'Kingfisher', '~> 4.8'

end
